package main
import("encoding/json";"fmt";"log";"net/http";"os";"strconv";"strings";"sync";"time")
type Courier struct{ID int `json:"id"`;Name string `json:"name"`;Status string `json:"status"`;Latitude *float64 `json:"latitude"`;Longitude *float64 `json:"longitude"`;UpdatedAt time.Time `json:"updated_at"`}
type Point struct{Latitude float64 `json:"latitude"`;Longitude float64 `json:"longitude"`;CreatedAt time.Time `json:"created_at"`}
var mu sync.RWMutex
var cs=map[int]*Courier{1:{ID:1,Name:"Курьер 1",Status:"free"},2:{ID:2,Name:"Курьер 2",Status:"free"},3:{ID:3,Name:"Курьер 3",Status:"free"}}
var tracks=map[int][]Point{}
var key string
func out(w http.ResponseWriter,n int,v any){w.Header().Set("Content-Type","application/json; charset=utf-8");w.WriteHeader(n);json.NewEncoder(w).Encode(v)}
func auth(w http.ResponseWriter,r *http.Request)bool{k:=r.Header.Get("X-API-Key");if key!=""&&k!=key{out(w,401,map[string]any{"ok":false,"error":"unauthorized"});return false};return true}
func health(w http.ResponseWriter,r *http.Request){out(w,200,map[string]any{"ok":true,"service":"SALOMAT Courier Server 0.3.1"})}
func list(w http.ResponseWriter,r *http.Request){mu.RLock();defer mu.RUnlock();out(w,200,[]*Courier{cs[1],cs[2],cs[3]})}
func api(w http.ResponseWriter,r *http.Request){
 s:=strings.Split(strings.Trim(strings.TrimPrefix(r.URL.Path,"/api/couriers/"),"/"),"/");if len(s)<2{out(w,404,nil);return};id,e:=strconv.Atoi(s[0]);if e!=nil||cs[id]==nil{out(w,404,nil);return}
 if s[1]=="track"&&r.Method=="GET"{mu.RLock();defer mu.RUnlock();out(w,200,tracks[id]);return}
 if !auth(w,r){return};if r.Method!="POST"{out(w,405,nil);return}
 if s[1]=="status"{var x struct{Status string `json:"status"`};if json.NewDecoder(r.Body).Decode(&x)!=nil||(x.Status!="free"&&x.Status!="busy"){out(w,400,nil);return};mu.Lock();cs[id].Status=x.Status;cs[id].UpdatedAt=time.Now().UTC();mu.Unlock();out(w,200,map[string]bool{"ok":true});return}
 if s[1]=="location"{var x struct{Latitude float64 `json:"latitude"`;Longitude float64 `json:"longitude"`};if json.NewDecoder(r.Body).Decode(&x)!=nil||x.Latitude < -90||x.Latitude>90||x.Longitude < -180||x.Longitude>180{out(w,400,nil);return};now:=time.Now().UTC();mu.Lock();a,b:=x.Latitude,x.Longitude;cs[id].Latitude=&a;cs[id].Longitude=&b;cs[id].UpdatedAt=now;tracks[id]=append(tracks[id],Point{a,b,now});if len(tracks[id])>1000{tracks[id]=tracks[id][len(tracks[id])-1000:]};mu.Unlock();out(w,200,map[string]bool{"ok":true});return};out(w,404,nil)
}
func courier(w http.ResponseWriter,r *http.Request){id,e:=strconv.Atoi(strings.Trim(strings.TrimPrefix(r.URL.Path,"/courier/"),"/"));if e!=nil||cs[id]==nil{http.NotFound(w,r);return};w.Header().Set("Content-Type","text/html; charset=utf-8");fmt.Fprintf(w,courierHTML,id,id)}
func home(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/"{http.NotFound(w,r);return};w.Header().Set("Content-Type","text/html; charset=utf-8");fmt.Fprint(w,dashHTML)}
func main(){key=os.Getenv("API_KEY");port:=os.Getenv("PORT");if port==""{port="8080"};http.HandleFunc("/health",health);http.HandleFunc("/api/couriers",list);http.HandleFunc("/api/couriers/",api);http.HandleFunc("/courier/",courier);http.HandleFunc("/",home);log.Printf("SALOMAT Courier Server 0.3.1 listening on :%s",port);log.Fatal(http.ListenAndServe("0.0.0.0:"+port,nil))}
const courierHTML=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>САЛОМАТ Курьер %d</title><style>*{box-sizing:border-box}body{margin:0;background:#f5f6f8;font-family:Arial;color:#222}.w{max-width:500px;margin:auto;padding:22px 16px}.logo{color:#188754;font-size:26px;font-weight:800}h1{font-size:22px}.c{background:white;padding:16px;border-radius:16px;margin:12px 0;box-shadow:0 2px 10px #0000000d}input,button{width:100%%;padding:14px;border-radius:11px;font-size:16px}.key{border:1px solid #ddd}.g{display:grid;grid-template-columns:1fr 1fr;gap:10px}.b{border:0;font-weight:700}.free{background:#dff5e8;color:#176b45}.busy{background:#eee4f8;color:#6639a0}.start{margin-top:12px;background:#188754;color:#fff}.stop{margin-top:8px;background:#eceff2}.small{font-size:13px;color:#6c7278;margin-top:8px;line-height:1.4}.state{font-weight:700;margin-bottom:8px}.ok{color:#188754}.bad{color:#c43b3b}</style></head><body><div class="w"><div class="logo">САЛОМАТ</div><h1>Курьер %d</h1><div class="c"><div class="small">API_KEY из Render</div><input id="k" class="key" type="password" placeholder="Вставьте секретный ключ"><div class="small">Ключ хранится только на этом телефоне.</div></div><div class="c"><div class="g"><button class="b free" onclick="status('free')">Свободен</button><button class="b busy" onclick="status('busy')">Занят</button></div></div><div class="c"><div id="s" class="state">GPS выключен</div><div id="p" class="small">Координат пока нет</div><button id="a" class="b start" onclick="start()">Начать работу / GPS</button><button id="z" class="b stop" onclick="stop()" disabled>Остановить GPS</button><div class="small">Разрешите браузеру точное местоположение. Для первого теста держите страницу открытой.</div></div></div><script>
const ID=Number(location.pathname.split('/').filter(Boolean).pop());let wid=null,busy=false,k=document.getElementById('k');k.value=localStorage.getItem('salomat_key')||'';k.onchange=()=>localStorage.setItem('salomat_key',k.value.trim());
function K(){let v=k.value.trim();if(!v){alert('Вставьте API_KEY из Render');throw 0}localStorage.setItem('salomat_key',v);return v}function S(t,ok){let e=document.getElementById('s');e.textContent=t;e.className='state '+(ok?'ok':'bad')}
async function post(a,x){let r=await fetch('/api/couriers/'+ID+'/'+a,{method:'POST',headers:{'Content-Type':'application/json','X-API-Key':K()},body:JSON.stringify(x)});if(r.status===401){S('Неверный API_KEY',false);throw 0}if(!r.ok){S('Ошибка связи с сервером',false);throw 0}}
async function status(v){try{await post('status',{status:v});S('Статус: '+(v==='free'?'Свободен':'Занят'),true)}catch(e){}}
async function pos(x){if(busy)return;busy=true;let a=x.coords.latitude,o=x.coords.longitude,ac=Math.round(x.coords.accuracy||0);document.getElementById('p').textContent=a.toFixed(6)+', '+o.toFixed(6)+' · точность ~'+ac+' м';try{await post('location',{latitude:a,longitude:o});S('GPS передаётся на сервер',true)}catch(e){}busy=false}
function err(e){S(e.code===1?'Нет разрешения на геолокацию':'Не удалось получить GPS',false)}
function start(){try{K()}catch(e){return}if(!navigator.geolocation){S('Геолокация не поддерживается',false);return}if(wid!==null)return;S('Получаем GPS…',true);wid=navigator.geolocation.watchPosition(pos,err,{enableHighAccuracy:true,maximumAge:5000,timeout:20000});a.disabled=true;z.disabled=false}
function stop(){if(wid!==null)navigator.geolocation.clearWatch(wid);wid=null;a.disabled=false;z.disabled=true;S('GPS выключен',false)}
</script></body></html>`
const dashHTML=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>САЛОМАТ — Курьеры</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>*{box-sizing:border-box}body{margin:0;font-family:Arial;background:#f6f7f9}header{height:60px;background:#fff;padding:18px;font-weight:800;color:#188754}.x{display:grid;grid-template-columns:300px 1fr;gap:12px;padding:12px}.panel{background:#fff;border-radius:14px;overflow:hidden}.list{padding:10px}.c{padding:12px;border:1px solid #e5e5e5;border-radius:10px;margin:7px 0;cursor:pointer}.name{font-weight:700}.meta{font-size:12px;color:#777;margin-top:5px}#map{height:calc(100vh - 84px);min-height:500px}@media(max-width:700px){.x{grid-template-columns:1fr}#map{height:60vh}}</style></head><body><header>САЛОМАТ — контроль курьеров 0.3.1</header><div class="x"><div class="panel"><div id="l" class="list"></div></div><div class="panel"><div id="map"></div></div></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
let m=L.map('map').setView([38.5598,68.7870],13),mk={},line=null;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(m);
async function track(id){let d=await(await fetch('/api/couriers/'+id+'/track')).json();if(line)m.removeLayer(line);if(d.length>1){line=L.polyline(d.map(x=>[x.latitude,x.longitude])).addTo(m);m.fitBounds(line.getBounds())}else if(mk[id])m.setView(mk[id].getLatLng(),16)}
async function refresh(){let d=await(await fetch('/api/couriers')).json(),l=document.getElementById('l');l.innerHTML='';d.forEach(c=>{let e=document.createElement('div');e.className='c';let t=c.updated_at&&!c.updated_at.startsWith('0001-')?new Date(c.updated_at).toLocaleTimeString():'нет сигнала';e.innerHTML='<div class="name">'+c.name+' — '+(c.status==='busy'?'Занят':'Свободен')+'</div><div class="meta">Последний сигнал: '+t+'</div>';e.onclick=()=>track(c.id);l.appendChild(e);if(c.latitude!=null){let p=[c.latitude,c.longitude];if(!mk[c.id])mk[c.id]=L.marker(p).addTo(m).bindPopup(c.name);else mk[c.id].setLatLng(p)}})}refresh();setInterval(refresh,5000);
</script></body></html>`